blog/urls.py
from django.urls import path
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from blogApp import views
from blogApp import  urls
from django.contrib import admin

urlpatterns=[
    # path('admin/', admin.site.urls),
    path('', include('blogApp.urls')),
]

blogApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
#     path('', views.index, name = 'index'),
     path('', views.login, name = 'login'),

    path('index/', views.index, name = 'index'),

    path('login/', views.login, name = 'login'),
    path('regist/', views.regist, name = 'regist'),

    path('search/', views.search, name = 'search'),
    path('manage/<slug:username>/', views.manage, name = 'manage'),
    path('edit/<slug:blogid>/', views.edit, name = 'edit'),
    path('info/<slug:username>/', views.info, name='edit'),
    path('editInfo/<slug:username>/', views.editInfo, name='editInfo'),
    path('edit/submit/<slug:username>/', views.submit, name='submit'),

    path('download/<slug:username>/', views.download, name = 'download'),
    
    path('personalIndex/<slug:username>/', views.personalIndex, name = 'personalIndex'),
    path('blogcontent/<int:blog_id>/', views.blog_content, name='content'),

    path('notification/<slug:username>/', views.notify, name = 'notify'),

    path('follow/<slug:username>/', views.follow, name = 'notify'),
    path('favourite/<slug:username>/', views.favourite, name = 'notify'),
    
    path('error/', views.error, name = 'error'),
    # path('manage/<string:username>', views.manage, name = 'manage'),
    # path('edit/<string:username>', views.edit, name = 'edit'),
    # path('info/<string:username>', views.info, name = 'edit'),
    # path('editInfo/<string:username>', views.editInfo, name = 'editInfo'),

    # path('blog/<int:blogID>/', views.blogContent, name = 'blogCotent'),
]

blogApp/models.py
from django.db import models
import markdown

# Create your models here.

# 用户表
class User(models.Model):
    user_id = models.BigAutoField(primary_key = True)

    name = models.CharField(max_length = 40)
    nickname = models.CharField(max_length = 40)
    password = models.CharField(max_length = 32)
    regist_time = models.DateTimeField()
    email = models.EmailField(null = True, blank = True)
    description = models.CharField(max_length = 100, null = True, blank = True)

    avatar = models.CharField(null= True,max_length= 100, default="https://raw.githubusercontent.com/oi-songer/oi-songer.github.io/master/portal.jpg")

    class Meta:
        db_table = 'User'

# 分类表
class Category(models.Model):
    cate_id = models.BigAutoField(primary_key = True)

    user = models.ForeignKey(User, on_delete = models.CASCADE)
    cate_name = models.CharField(max_length = 40)

    class Meta:
        db_table = 'Category'

# 博客内容表
class Blog(models.Model):
    blog_id = models.BigAutoField(primary_key = True)

    user = models.ForeignKey(User, on_delete = models.CASCADE )
    cate = models.ForeignKey(Category, on_delete = models.CASCADE )
    content = models.TextField()
    title = models.CharField(max_length = 100)
    view_num = models.IntegerField()
    like_num = models.IntegerField()
    create_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 将数据库里存储的markdown代码转化为HTML
    def toHTML(self):
        return markdown.markdown(self.content.__str__(),
            extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            ])

    # 返回博客的Preview部分，使用HTML格式
    def preview(self):
        str = self.content.__str__()
        if (str.find("<!--more-->")!=-1):
            str = markdown.markdown(str[0:str.index("<!--more-->")],
                extensions=[
                # 包含 缩写、表格等常用扩展
                'markdown.extensions.extra',
                # 语法高亮扩展
                'markdown.extensions.codehilite',
                ])
        else:
            str = "无预览"
        return str

    class Meta:
        db_table = 'Blog'

# 评论表
class Comment(models.Model):
    comment_id = models.BigAutoField(primary_key = True)

    blog = models.ForeignKey(Blog, on_delete = models.CASCADE )
    user = models.ForeignKey(User, on_delete = models.CASCADE )
    content = models.CharField(max_length = 600)
    time = models.DateTimeField()

    class Meta:
        db_table = 'Comment'

# 标签表
class Tag(models.Model):
    tag_id = models.BigAutoField(primary_key = True)

    tag_name = models.CharField(max_length = 40)

    class Meta:
        db_table = 'Tag'

# 博客-标签表
class BlogTag(models.Model):
    blog_tag_id = models.BigAutoField(primary_key = True)

    blog = models.ForeignKey(Blog, on_delete = models.CASCADE )
    tag = models.ForeignKey(Tag, on_delete = models.CASCADE )

    class Meta:
        db_table = 'BlogTag'



# 收藏夹表
class Favourite(models.Model):
    favourite_id = models.BigAutoField(primary_key = True)

    user = models.ForeignKey(User, on_delete = models.CASCADE )
    blog = models.ForeignKey(Blog, on_delete = models.CASCADE )

    class Meta:
        db_table = 'Favourite'

# 关注表
class Follow(models.Model):
    follow_id = models.BigAutoField(primary_key = True)

    # 由于两个外键都指向了User，所以需要设置related_name
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'follows' )
    fld_user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'followers' )

    class Meta:
        db_table = 'Follow'

# 通知表
class Notification(models.Model):
    noti_id = models.BigAutoField(primary_key = True)

    user = models.ForeignKey(User, on_delete = models.CASCADE )
    content = models.CharField(max_length = 400)
    unread = models.BooleanField(default = True)

    class Meta:
        db_table = 'Notification'

# Cookie表
class Cookie(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE )
    cookie = models.CharField(max_length = 20)

    class Meta:
        db_table = 'Cookie'

blogApp/views.py
from .models import *
from django.template import RequestContext
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django import forms
from django.utils import timezone
from django.db.models import Q
from functools import *
import random
from django.http import JsonResponse

from django.db.models import Max,Min

#表单
class UserForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=100)
    password = forms.CharField(label='密码',widget=forms.PasswordInput())

class ReForm(forms.Form):
    username = forms.CharField(label='用户名',max_length=100)
    password1 = forms.CharField(label='密码',widget=forms.PasswordInput())
    password2 = forms.CharField(label='确认密码', widget=forms.PasswordInput())

class SearchForm(forms.Form):
    keywords = forms.CharField(label = "关键字", max_length = 100)

def getUserByCOOKIE(cook):
    return Cookie.objects.get( cookie = cook ).user

#注册
def regist(req):
    if req.method == 'POST':

            username = req.POST.get('username',None)
            password1 = req.POST.get('password', None)
            password2 = req.POST.get('repeatpassword', None)

            ceshi = User.objects.filter(name = username)
            if ceshi:
                return HttpResponse('账号重复')

            if(password1!=password2):
                return HttpResponse('regist failed!!')
            #添加到数据库
            time_now = timezone.now()

            # md5加密
            import hashlib
            hl = hashlib.md5()
            hl.update(password1.encode(encoding='utf-8'))
            storepassword = hl.hexdigest()

            User.objects.create(name= username,password=storepassword,regist_time=time_now,nickname=username)
            response=HttpResponseRedirect('/index')

            auser = User.objects.filter(name__exact=username, password__exact=storepassword)
            loginuserid1 = auser.values_list('user_id', flat=True)
            loginuserid = loginuserid1[0]

            seed = "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_+=-"
            sa = []
            for i in range(20):
                sa.append(random.choice(seed))
            salt = ''.join(sa)
            print(salt)
            response.set_cookie('userid', salt, 3600)

            # 保存到数据库（salt，userid(loginuserid))
            loginuser = User.objects.get(user_id=loginuserid)
            cookie = Cookie()
            print(loginuserid)
            cookie.user = loginuser
            cookie.cookie = salt
            cookie.save()

            return response

    return render(req, 'blogApp/regist.html')

#登陆
def login(req):
    if req.method == 'POST':

        username = req.POST.get('username',None)
        password = req.POST.get('password',None)


        import hashlib
        h2 = hashlib.md5()
        h2.update(password.encode(encoding='utf-8'))
        storepassword = h2.hexdigest()
        #获取的表单数据与数据库进行比较
        auser = User.objects.filter(name__exact = username,password__exact = storepassword)

        if auser:
            #比较成
            response = HttpResponseRedirect('/index')
            #将username写入浏览器cookie,失效时间为3600
            loginuserid1 = auser.values_list('user_id',flat=True)
            loginuserid = loginuserid1[0]

            # 随机串
            seed = "1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()_+=-"
            sa = []
            for i in range(20):
                sa.append(random.choice(seed))
            salt = ''.join(sa)
            print(salt)
            response.set_cookie('userid',salt,3600)

                #保存到数据库（salt，userid(loginuserid))
            loginuser = User.objects.get(user_id=loginuserid)
            cookie = Cookie()
            print(loginuserid)
            cookie.user = loginuser
            cookie.cookie = salt
            cookie.save()

            return response
        else:
                #比较失败，还在login
            return HttpResponseRedirect('/login')
    else:
        uf = UserForm()
    return render(req,'blogApp/Login.html')

#退出
def logout(req):
    response = HttpResponse('logout !!')
    #清理cookie里保存username
    response.delete_cookie('username')
    return response


# 首页

def index(req):

    blogList = sorted(Blog.objects.all(), key = lambda x:-x.view_num)[:10]
    userList = sorted(
        User.objects.all(), key = lambda x:-(
            sum( 
                map(lambda x:x.view_num, x.blog_set.all())
                )
            )
        )[:20]

    cock = req.COOKIES.get('userid', None)
    if (cock == None):
        currentuser = None
    if (cock!=None):
        currentuser = getUserByCOOKIE(cock)
    dic = {}
    dic['userList'] = userList
    dic['blogList'] = blogList
    dic['currentUser'] = currentuser

    return render(req, "blogApp/index.html", dic)

# 搜索结果
def search(req):
    req.encoding = 'utf-8'

    queryList = Blog.objects.all()

    dic = {}

    if('keywords' in req.GET and req.GET['keywords'] == ''):
        return HttpResponse('请输入关键词')

    
    if ('keywords' in req.GET and not req.GET['keywords'] == ''):
        queryList = queryList.filter( 
            reduce( lambda x, y: x & y, map( 
                lambda x: (Q(title__icontains = x) | Q(title__icontains = x)) , req.GET['keywords'].split(' '))
            )
        )
        dic['keywords'] = req.GET['keywords']

    if ('categoryid' in req.GET and not req.GET['categoryid'] == ''):
        queryList = queryList.filter(category_id = req.GET['categoryid'])
        dic['category'] = Category.objects.get(category_id = req.GET['category_id'])
    
    if ('userid' in req.GET and not req.GET['userid'] == ''):
        queryList = queryList.filter(user_id = req.GET['userid'])
        dic['user'] = User.objects.get(user_id = req.GET['userid'])

    if ('tagid' in req.GET and not req.GET['tagid'] == ''):
        queryList = queryList.filter(blogtag__tag__tag_id__contains = req.GET['tagid'])
        dic['tag'] = Tag.objects.get(tag_id = req.GET['tagid'])

    cock = req.COOKIES.get('userid', None)
    if (cock != None):
        currentuser = getUserByCOOKIE(cock)
    else:
        currentuser = None
    dic['currentUser'] = currentuser
    dic['blogList'] = list(queryList)
    print(dic)

    return render(req, 'blogApp/search.html', dic)

def edit(req,blogid):
    blogid = int(blogid)
    #1.标签和分类的问题
    #blogid 查出userid然后和cookie进行对比，
    #找cookie对应的id
    useridsalt = req.COOKIES.get('userid',None)
    if (useridsalt == None):
        return HttpResponseRedirect('/error')
    c_userid = Cookie.objects.get(cookie__exact=useridsalt).user_id
    #不加_id的话是一个对象，加的话是一贯制
    #找用户名对应的id

    #若blogid不为0则需要将博客内容读出
    #不等于0，编辑再完善
    if (blogid!=0):

        #验证正确性
        u_userid = Blog.objects.get(blog_id=blogid).user_id
        if (u_userid != c_userid):
            return HttpResponseRedirect('/error')

        #从数据库中读取原来的博客题目内容分类等
        catset1 = Category.objects.filter(user_id=c_userid)
        catset = catset1.values_list('cate_name', flat=True)
        blogset = Blog.objects.filter(blog_id=blogid)
        reblog1 = list(blogset)
        reblog = reblog1[0]
        catename = Category.objects.get(cate_id=reblog.cate_id).cate_name
        #从数据库中读取tags信息
        pblogtagset = BlogTag.objects.filter(blog_id=blogid)
        blogtagset = list(pblogtagset)
        str = ''
        for i in blogtagset:
            tagnameqs = Tag.objects.filter(tag_id=i.tag_id)
            if tagnameqs :
                tagname = Tag.objects.get(tag_id=i.tag_id).tag_name
                str = str +tagname + ','
                print(str)
        str = str.rstrip(',')
        print(str)



        #从前端获取数据
        title = req.POST.get('title', None)
        text = req.POST.get('text', None)
        mytags = req.POST.get('mytags', None)
        aclass = req.POST.get('class', None)

        if (title != None):
            # 将Blog进行更新,本来就有blogid
            # 数据转换，获取userid,classid
            #create blog
            cate_id = Category.objects.get(cate_name__exact=aclass).cate_id
            time_now = timezone.now()
            Blog.objects.filter(blog_id=blogid).update(content=text, title=title,
                                modified_time=time_now, cate_id=cate_id)
            #update tags and blogtag,mytags是新输入的tags
            #新输入的tags,列表格式
            l = mytags.split(',')
            inserttags = []
            for i in l:
                inserttags.append(i.lstrip(' ').rstrip(' '))

            #旧的删除
            for i in blogtagset:
                BlogTag.objects.filter(blog_id=blogid, tag_id=i.tag_id).delete()
            #对每一个新的i，若在tags表里有，如没有，
            for i in inserttags:
                result = Tag.objects.filter(tag_name=i)
                if result:
                    #吧它加上，便于实现
                    everyid = Tag.objects.get(tag_name=i).tag_id
                    BlogTag.objects.create(blog_id=blogid,tag_id=everyid)
                else:
                    Tag.objects.create(tag_name=i)
                    everyid = Tag.objects.get(tag_name=i).tag_id
                    BlogTag.objects.create(blog_id=blogid, tag_id=everyid)
        user = User.objects.get(user_id=c_userid)
        return render(req, 'blogApp/edit.html', {'catset': catset, 'reblog': reblog, 'blogid': blogid,'catename':catename,'str': str,'user':user ,'currentUser':user})

    #等于零，新的
    else:
        catset1 = Category.objects.filter(user_id=c_userid)
        catset = catset1.values_list('cate_name', flat=True)

        # 前端传后端   ，不空再传
        title = req.POST.get('title', None)
        text = req.POST.get('text', None)
        mytags = req.POST.get('mytags', None)
        aclass = req.POST.get('class', None)
        print(title,text,mytags,aclass)

        if (title != None):
            # 将Blog存进数据库,给出blogid
            # 数据转换，获取userid,classid
            cate_id = Category.objects.get(cate_name__exact=aclass).cate_id
            time_now = timezone.now()

blogApp/templates/blogApp/BlogContent.html
{% extends "blogApp/_base_with_rightbar.html" %}

<!--使用到的变量：
rightbar:
    currentUser
    user
    tag
    category
    alreadyFollowed

blogContent:
    blog
-->

<!--title-->
{% block title %} {{ blog.title }} {% endblock %}

<!--pagetitle-->
{% block pagetitle %} {{ blog.title }} {% endblock %}

<!--article-->
{% block article %}
<article>
    <div style="text-align:right">
        <p>阅读量：{{blog.view_num}} 评论量：{{blog.comment_set.count}}</p>
        <p>
            <h5>
                {% for tag in blogTagList %}
                <span class="label label-success" style="margin:5px">
                    <a class="label-link" href="/search?userid={{user.user_id}}&tagid={{tag.tag_id}}">
                        {{tag.tag_name}}</a>
                </span> {% endfor %}
            </h5>
        </p>
    </div>
    <div style="word-break:break-all; padding-bottom:20px;">
        {{ blog.toHTML | safe }}
    </div>

    <div style="text-align:right">
        <div style="float:left">

            {% ifequal currentUser.user_id 1 %}

            <button class="btn btn-danger" name="deleteBlog" onclick="delblog( {{ blog.blog_id }} )">删除该博客</button> {% endifequal %}
        </div>

        收藏数：{{blog.favourite_set.count}}
        <br>
        <form style="text-align:center" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %} {% if alreadyFavourite %}
            <input class="btn btn-primary" type="submit" style="width:80px;float: right;margin-bottom: 10px" name="favourite" value="取消收藏" /> {% endif %} {% if not alreadyFavourite%}
            <input class="btn btn-primary" type="submit" style="width:80px;float: right;margin-bottom: 10px" name="favourite" value="收藏" /> {% endif %}
        </form>

    </div>

</article>

{% block comment %}

<div style="padding-top:10px; margin-bottom:20px">
    <form method="POST">
        {% csrf_token %}
        <input type="text" style="width:100%; min-height:100px; padding-bottom: 10px" name="comment-text">
        <input style="margin-left: 92%; margin-top: 5px;" type="submit" class="btn btn-info" value="评论">
    </form>
</div>

{% if not flag %}
<p>暂无评论</p>
{% endif %} {% for comment in page.object_list %}
<div class="panel panel-default" style="margin-top:5px; margin-bottom:5px">
    <div class="panel-heading">
        <a href="/personalIndex/{{comment.user.name}}">{{comment.user.name}}</a> in {{comment.time}}
    </div>
    <div style="float:right">

        {% ifequal currentUser.user_id 1 %}

        <button class="btn btn-danger" name="deleteBlog" onclick="delcomment({{comment.comment_id}})">删除该评论</button> {% endifequal %}
    </div>
    <div class="panel-body">
        {{comment.content}}
    </div>

</div>
{% endfor %}

<section>
    <ul class="pagination">
        {# 如果当前页还有上一页 #} {% if page.has_previous %}
        <li>
            {# 点击a标签，跳转到上一页链接 ?index 为地址后面拼接的参数 #}
            <a href="?index={{page.previous_page_number}}">上一页</a>
        </li>
        {% else %} {# 如果没有上一页， 则上一页按钮不可点击 #}
        <li class="disabled">
            <a href="#">上一页</a>
        </li>
        {% endif %} {% for page_number in paginator.page_range %} {# 获取当前页的页码 #} {% if page_number == page.number %} {# 如果是当前页的话，选中 #}
        <li class="active">
            <a href="?index={{page_number}}">{{page_number}}</a>
        </li>
        {% else %}
        <li>
            <a href="?index={{page_number}}">{{page_number}}</a>
        </li>
        {% endif %} {% endfor %} {% if page.has_next %}
        <li>
            <a href="?index={{page.next_page_number}}">下一页</a>
        </li>
        {% else %}
        <li class="disabled">
            <a href="#">下一页</a>
        </li>
        {% endif %}
    </ul>
</section>
<script>
    function delblog(blogid) {
        var post_data_delblog = {
            "blogtodel": blogid,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        };
        $.ajax({
            url: "/blogcontent/{{ blog.blog_id }}/",
            type: "POST",
            data: post_data_delblog,
            success: function(data) {
                window.location.href = '/index/'
            }
        });
        window.alert("删除成功")

    }

    function delcomment(commentid) {
        var post_data_comment = {
            "comtodel": commentid,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        };
        $.ajax({
            url: "/blogcontent/{{ blog.blog_id }}/",
            type: "POST",
            data: post_data_comment,
            success: function() {
                window.location.href = "/blogcontent/{{ blog.blog_id }}/"
            }
        });


    }
</script>
{% endblock %} {% endblock %}

blogApp/templates/blogApp/Register.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <link href="/static/css/Register.css" type="text/css" rel="stylesheet">
    <title>登陆界面</title>
</head>

<body background="/static/images/head.jpg">
    <div id="Login_box" opacity="0.9">
        <h2 style="padding-top: 40px">欢迎注册</h2>
        <img id="head_img" src="/static/images/bg.jpg">
        <p>念念不忘，必有回响</p>
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %} {{uf1.as_p}}
            <input type="submit" value="ok" />
        </form>
        <a href="/login/"><span>返回</span></a>

    </div>
</body>

</html>

blogApp/templates/blogApp/_base_with_footer.html
{% extends "blogApp/_base.html" %} {% block footer %}
<link href="/static/css/footer-static-bottom.css" rel="stylesheet">
<footer class="blog-footer">
    <p>Blog built by <a href="https://github.com/blogdevteam">BlogDevTeam</a></p>
    <p>
        <a href="#">
            Back to top.
        </a>
    </p>
</footer>
{% endblock %}

blogApp/templates/blogApp/edit.html
{% extends "blogApp/_base_with_header.html" %}
<!--extends-->

<!--title-->
{% block title %} 编辑 {% endblock %}

<!--pagetitle-->
{% block pagetitle %} 编辑博客 {% endblock %} {% block main %}

<script src="/static/css/jquery-3.4.1.min.js"></script>
<link href="/static/css/rightbar.css" rel="stylesheet">
<link href="https://cdn.bootcss.com/bootstrap-select/1.12.4/css/bootstrap-select.min.css" rel="stylesheet">

<div style="float:left; width:70%; padding-left:10px; margin-bottom:20px">
    <h4>标题：</h4><input type="text" class="form-control" style="width:70%" id="title" value={{ reblog.title }}>
    <br>

    <h4>内容：</h4>
    <textarea class="form-control" style="height:310px; resize:none" id="text">{{ reblog.content }}</textarea>
</div>

<div style="float:right; width:30%; padding-right:10px" class="rightbar rightbar-darker">

    <div style="float:right">
        <a href="/manage/{{currentUser.name}}">返回管理界面</a>
    </div>

    <br>
    <br>
    <br>

    <h4>分类：</h4>
    <div style="margin-left:10px">

        <select id = "class">
                {% for cat in catset %}
                    {% if cat == catename %}
                    <option value="{{ cat}}" selected >{{ cat }}</option>
                    {% endif %}
                    {% if cat != catename %}
                    <option value="{{ cat}}" >{{ cat }}</option>
                    {% endif %}
                {% endfor %}
            </select>
    </div>

    <br>
    <br>
    <br>
    <br>

    <h4>标签：</h4>
    <div>
        <input type="text" value="{{str}}" class="form-control" id="mytags" placeholder="请使用“，”分隔">
    </div>
    <br>
    <br>
    <br>
    <br>
    <div style="text-align: center">
        <button class="btn btn-info" onclick="givecontent()">提交</button>
    </div>
</div>

<script>
    function givecontent() {
            var post_data = {
                "title": document.getElementById("title").value,
                "text": document.getElementById("text").value,
                "mytags":document.getElementById("mytags").value,
                "class":document.getElementById("class").value,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            };
            $.ajax({
                url: "/edit/{{ blogid }}/",
                type: "POST",
                data: post_data,
            });
            document.getElementById("title").value = ''
            document.getElementById("text").value = ''
            document.getElementById("mytags").value = ''
            document.getElementById("class").value = ''
            window.alert("发布成功")
        }
</script>


{% endblock %}

blogApp/templates/blogApp/manage.html
{% extends "blogApp/_base_with_header.html" %}
<!--extends-->

<!--title-->
{% block title %} 博客管理 {% endblock %}

<!--pagetitle-->
{% block pagetitle %} 博客管理 {% endblock %}

<!--内容-->
{% block main %}


<link href="/static/css/rightbar.css" rel="stylesheet">

<div style="float:left; width:30%; padding-right:10px" class="rightbar rightbar-darker">
    <h2>
        分类
    </h2>

    <ul id="category-list">
        {% for cate,value in catedic.items %}
        <li>
            {% for foo in recateset %} {% if foo.cate_name == cate %}
            <label>
                        {{ cate }}({{ value }})
                        </label> {% endif %} {% endfor %} {% if value == 0 %} {% for i in recateset %} {% if i.cate_name == cate %}
            <button class="btn btn-sm btn-info" onclick="delcate({{ i.cate_id }})">
                        删除
                    </button> {% endif %} {% endfor %} {% endif %}
        </li>
        {% endfor %}
    </ul>


    <input id="cate" type="text">
    <input class="btn btn-info" onclick="addcate()" type="button" value="添加分类" style="margin-left: 10px; margin-right: 10px">

</div>

<div style="float:right; width:70%; padding-left:10px">

    <div style="float:left">
        <h3>
            我的博客：
        </h3>
    </div>


    <div style="float:right; margin-top:15px">
        <form method="GET">
            <input type="text" name="keywords">
            <input type="submit" value="搜索" class="btn btn-sm btn-info">
        </form>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th style="width:40%">
                    标题
                </th>
                <th>
                    浏览数
                </th>
                <th>
                    收藏数
                </th>
                <th>
                    操作
                </th>
                <th>
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            {% for blog in blogList %}
            <tr>
                <td style="width:40%">
                    <a href='blogcontent/{{blog.blog_id}}/'>
                    {{blog.title}}
                    </a>
                </td>
                <td>
                    {{blog.view_num}}
                </td>
                <td>
                    {{blog.favourite_set.count}}
                </td>
                <td>
                    <a href="/edit/{{blog.blog_id}}"> 编辑 </a>
                </td>
                <td>
                    <button class="btn btn-sm btn-danger" onclick="deleteblog({{ blog.blog_id}})"> 删除 </button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


</div>
<script>
    function deleteblog(blogoneid) {
        var post_data_del = {
            "blogone": blogoneid,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        };
        $.ajax({
            url: "/manage/{{ user.name }}/",
            type: "POST",
            data: post_data_del,
        });

        location.reload()
    }

    function addcate() {
        var post_data_addcate = {
            "catename": document.getElementById("cate").value,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        };
        $.ajax({
            url: "/manage/{{ user.name }}/",
            type: "POST",
            data: post_data_addcate,
        });
        window.alert("添加成功")
        location.reload()

    }

    function delcate(cateid) {
        var post_data_delcate = {
            "catetodel": cateid,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        };
        $.ajax({
            url: "/manage/{{ user.name }}/",
            type: "POST",
            data: post_data_delcate,
        });
        window.alert("删除成功")
        location.reload()
    }

    function filtercate(cateid) {
        var post_data_fil = {
            "catetofil": cateid,
            csrfmiddlewaretoken: '{{ csrf_token }}'
        };
        $.ajax({
            url: "/manage/{{ username }}/",
            type: "POST",
            data: post_data_fil,
            success: function() {
                window.location.reload()
            }
        });

    }
</script>

{% endblock %}